# Site settings
title: Il Gusto
name: Cipolletta Vincenzo
phone: +43 (0) 664 - 73712148
subtitle: Italienische Spezialitäten
address: "Mautweg 7, 9232 Rosegg"
opening_hours:
  title: Öffnungszeiten
  mo:
    title: "Mo"
    hours: "15:00 - 18:30"
  di:
    title: "Di"
    hours: "08:30 - 13:00 & 15:00 - 18:30"
  mi:
    title: "Mi"
    hours: "08:30 - 13:00 & 15:00 - 18:30"
  do:
    title: "Do"
    hours: "08:30 - 13:00"
  fr:
    title: "Fr"
    hours: "08:30 - 13:00 & 15:00 - 18:30"
  sa:
    title: "Sa"
    hours: "08:30 - 13:00"
uid: ATU63006507
email: enzomoda@aon.at
description: > # this means to ignore newlines until "baseurl:"
  Italienische Spezialitäten<br>
  Mautweg 7, 9232 Rosegg<br>
  <br>
  Öffnungszeiten:<br>
  MO: 15:00 - 18:30<br>
  DI, MI, FR: 08:30 - 13:00 und 15:00 - 18:30<br>
  DO, SA: 08:30 - 13:00<br>
baseurl: "/il-gusto" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments
